services:
  # Backend service
  backend:
    build: ./backend
    container_name: traffic-light-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    networks:
      - traffic-light-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
        VITE_WS_URL: ws://localhost:8000
    container_name: traffic-light-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    networks:
      - traffic-light-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  traffic-light-network:
    driver: bridge 