/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * API for managing users and their todos. Now with WebSockets!
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoardCreate
 */
export interface BoardCreate {
    /**
     * 
     * @type {string}
     * @memberof BoardCreate
     */
    name: string;
}

/**
 * Check if a given object implements the BoardCreate interface.
 */
export function instanceOfBoardCreate(value: object): value is BoardCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BoardCreateFromJSON(json: any): BoardCreate {
    return BoardCreateFromJSONTyped(json, false);
}

export function BoardCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function BoardCreateToJSON(json: any): BoardCreate {
    return BoardCreateToJSONTyped(json, false);
}

export function BoardCreateToJSONTyped(value?: BoardCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

