/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * API for managing users and their todos. Now with WebSockets!
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoardUpdate
 */
export interface BoardUpdate {
    /**
     * 
     * @type {string}
     * @memberof BoardUpdate
     */
    name?: string | null;
}

/**
 * Check if a given object implements the BoardUpdate interface.
 */
export function instanceOfBoardUpdate(value: object): value is BoardUpdate {
    return true;
}

export function BoardUpdateFromJSON(json: any): BoardUpdate {
    return BoardUpdateFromJSONTyped(json, false);
}

export function BoardUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function BoardUpdateToJSON(json: any): BoardUpdate {
    return BoardUpdateToJSONTyped(json, false);
}

export function BoardUpdateToJSONTyped(value?: BoardUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

