/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * API for managing users and their todos. Now with WebSockets!
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const InvitationStatus = {
    Pending: 'pending',
    Accepted: 'accepted',
    Declined: 'declined',
    Revoked: 'revoked'
} as const;
export type InvitationStatus = typeof InvitationStatus[keyof typeof InvitationStatus];


export function instanceOfInvitationStatus(value: any): boolean {
    for (const key in InvitationStatus) {
        if (Object.prototype.hasOwnProperty.call(InvitationStatus, key)) {
            if (InvitationStatus[key as keyof typeof InvitationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InvitationStatusFromJSON(json: any): InvitationStatus {
    return InvitationStatusFromJSONTyped(json, false);
}

export function InvitationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationStatus {
    return json as InvitationStatus;
}

export function InvitationStatusToJSON(value?: InvitationStatus | null): any {
    return value as any;
}

export function InvitationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): InvitationStatus {
    return value as InvitationStatus;
}

